// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorAcademia.Infraestrutura.Dados;

#nullable disable

namespace SimuladorAcademia.Infraestrutura.Migrations
{
    [DbContext(typeof(SimuladorAcademiaDbContext))]
    [Migration("20251106022608_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContagemDeAulasMensais")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoDePlanoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoDePlanoId");

                    b.HasIndex("Email", "Nome")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoEmMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Participantes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TipoDeAulaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoDeAulaId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.HistoricoReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("HistoricosReserva");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("AlunoId", "AulaId")
                        .IsUnique();

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.TipoDeAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposAula");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.TipoDePlano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApagadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteAula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposPlano");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aluno", b =>
                {
                    b.HasOne("SimuladorAcademia.Dominio.Entidades.TipoDePlano", "TipoDePlano")
                        .WithMany("Alunos")
                        .HasForeignKey("TipoDePlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDePlano");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aula", b =>
                {
                    b.HasOne("SimuladorAcademia.Dominio.Entidades.TipoDeAula", "TipoDeAula")
                        .WithMany("Aulas")
                        .HasForeignKey("TipoDeAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDeAula");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.HistoricoReserva", b =>
                {
                    b.HasOne("SimuladorAcademia.Dominio.Entidades.Reserva", "Reserva")
                        .WithMany("HistoricoReserva")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Reserva", b =>
                {
                    b.HasOne("SimuladorAcademia.Dominio.Entidades.Aluno", "Aluno")
                        .WithMany("Reservas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimuladorAcademia.Dominio.Entidades.Aula", "Aula")
                        .WithMany("Reservas")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aluno", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Aula", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.Reserva", b =>
                {
                    b.Navigation("HistoricoReserva");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.TipoDeAula", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("SimuladorAcademia.Dominio.Entidades.TipoDePlano", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
